package service;

import model.Continent;
import model.Player;
import model.Territory;
import org.easymock.EasyMock;
import org.junit.jupiter.api.Test;
import java.util.List;
import model.GameState;
import service.ReinforcementService;

import static org.junit.jupiter.api.Assertions.*;

public class ReinforcementServiceTest {

    @Test
    void shouldReturnZeroBonusWhenPlayerControlsNoFullContinent() {
        // player has 5/6 in AFRICA continent, one in Asia, no bonus
        ReinforcementService rs = new ReinforcementService();
        Territory t1 = new Territory();
        Territory t2 = new Territory();
        Territory t3 = new Territory();
        Territory t4 = new Territory();
        Territory t5 = new Territory();
        Territory t6 = new Territory();
        GameState gameState = new GameState();
        List<Territory> controlled_territories = List.of(t1, t2, t3, t4, t5, t6);
        Player player1 = new Player(1, "A", "Red", 0, controlled_territories);
        t1.setOwner(player1);
        t2.setOwner(player1);
        t3.setOwner(player1);
        t4.setOwner(player1);
        t5.setOwner(player1);
        t6.setOwner(player1);
        t1.setArmyCount(3);
        t2.setArmyCount(3);
        t3.setArmyCount(3);
        t4.setArmyCount(3);
        t5.setArmyCount(3);
        t6.setArmyCount(3);
        t1.setContinent(Continent.AFRICA);
        t2.setContinent(Continent.AFRICA);
        t3.setContinent(Continent.AFRICA);
        t4.setContinent(Continent.AFRICA);
        t5.setContinent(Continent.AFRICA);
        t6.setContinent(Continent.ASIA);
        t1.setName("Egypt");
        t2.setName("Congo");
        t3.setName("Madagascar");
        t4.setName("East Africa");
        t5.setName("South Africa");
        t6.setName("Japan");
        int actual_bonus = rs.calculateContinentBonus(player1, gameState);
        assertEquals(0, actual_bonus);
    }

    @Test
    void shouldReturnCorrectBonusWhenPlayerControlsOneContinent() {
        // player has control over one full continent plus one in every other continent
        // Africa
        ReinforcementService rs = new ReinforcementService();
        Territory t1 = new Territory();
        Territory t2 = new Territory();
        Territory t3 = new Territory();
        Territory t4 = new Territory();
        Territory t5 = new Territory();
        Territory t6 = new Territory();
        GameState gameState = new GameState();
        List<Territory> controlled_territories = List.of(t1, t2, t3, t4, t5, t6);
        Player player1 = new Player(1, "A", "Red", 0, controlled_territories);
        t1.setOwner(player1);
        t2.setOwner(player1);
        t3.setOwner(player1);
        t4.setOwner(player1);
        t5.setOwner(player1);
        t6.setOwner(player1);
        t1.setArmyCount(3);
        t2.setArmyCount(3);
        t3.setArmyCount(3);
        t4.setArmyCount(3);
        t5.setArmyCount(3);
        t6.setArmyCount(3);
        t1.setContinent(Continent.AFRICA);
        t2.setContinent(Continent.AFRICA);
        t3.setContinent(Continent.AFRICA);
        t4.setContinent(Continent.AFRICA);
        t5.setContinent(Continent.AFRICA);
        t6.setContinent(Continent.AFRICA);
        t1.setName("Egypt");
        t2.setName("Congo");
        t3.setName("Madagascar");
        t4.setName("East Africa");
        t5.setName("South Africa");
        t6.setName("Northern Africa");
        int actual_bonus = rs.calculateContinentBonus(player1, gameState);
        assertEquals(3, actual_bonus);

        // Australia
        Territory t12 = new Territory();
        Territory t22 = new Territory();
        Territory t32 = new Territory();
        Territory t42 = new Territory();
        List<Territory> controlled_territories2 = List.of(t12, t22, t32, t42);
        Player player2 = new Player(1, "A", "Red", 0, controlled_territories2);
        t12.setOwner(player2);
        t22.setOwner(player2);
        t32.setOwner(player2);
        t42.setOwner(player2);
        t12.setArmyCount(3);
        t22.setArmyCount(3);
        t32.setArmyCount(3);
        t42.setArmyCount(3);
        t12.setContinent(Continent.AUSTRALIA);
        t22.setContinent(Continent.AUSTRALIA);
        t32.setContinent(Continent.AUSTRALIA);
        t42.setContinent(Continent.AUSTRALIA);
        t12.setName("Indonesia");
        t22.setName("New Guinea");
        t32.setName("Western Australia");
        t42.setName("Eastern Australia");
        int actual_bonus2 = rs.calculateContinentBonus(player2, gameState);
        assertEquals(2, actual_bonus2);

        // South America
        Territory t13 = new Territory();
        Territory t23 = new Territory();
        Territory t33 = new Territory();
        Territory t43 = new Territory();
        List<Territory> controlled_territories3 = List.of(t13, t23, t33, t43);
        Player player3 = new Player(1, "A", "Red", 0, controlled_territories3);
        t13.setOwner(player3);
        t23.setOwner(player3);
        t33.setOwner(player3);
        t43.setOwner(player3);
        t13.setArmyCount(3);
        t23.setArmyCount(3);
        t33.setArmyCount(3);
        t43.setArmyCount(3);
        t13.setContinent(Continent.SOUTH_AMERICA);
        t23.setContinent(Continent.SOUTH_AMERICA);
        t33.setContinent(Continent.SOUTH_AMERICA);
        t43.setContinent(Continent.SOUTH_AMERICA);
        t13.setName("Peru");
        t23.setName("Brazil");
        t33.setName("Venezuela");
        t43.setName("Argentina");
        int actual_bonus3 = rs.calculateContinentBonus(player3, gameState);
        assertEquals(2, actual_bonus2);

        // North America
        Territory t14 = new Territory();
        Territory t24 = new Territory();
        Territory t34 = new Territory();
        Territory t44 = new Territory();
        Territory t54 = new Territory();
        Territory t64 = new Territory();
        Territory t74 = new Territory();
        Territory t84 = new Territory();
        Territory t94 = new Territory();
        List<Territory> controlled_territories4 = List.of(t14, t24, t34, t44, t54, t64, t74, t84, t94);
        Player player4 = new Player(1, "A", "Red", 0, controlled_territories4);
        t14.setOwner(player4);
        t24.setOwner(player4);
        t34.setOwner(player4);
        t44.setOwner(player4);
        t54.setOwner(player4);
        t64.setOwner(player4);
        t74.setOwner(player4);
        t84.setOwner(player4);
        t94.setOwner(player4);
        t14.setArmyCount(3);
        t24.setArmyCount(3);
        t34.setArmyCount(3);
        t44.setArmyCount(3);
        t54.setArmyCount(3);
        t64.setArmyCount(3);
        t74.setArmyCount(3);
        t84.setArmyCount(3);
        t94.setArmyCount(3);
        t14.setContinent(Continent.NORTH_AMERICA);
        t24.setContinent(Continent.NORTH_AMERICA);
        t34.setContinent(Continent.NORTH_AMERICA);
        t44.setContinent(Continent.NORTH_AMERICA);
        t54.setContinent(Continent.NORTH_AMERICA);
        t64.setContinent(Continent.NORTH_AMERICA);
        t74.setContinent(Continent.NORTH_AMERICA);
        t84.setContinent(Continent.NORTH_AMERICA);
        t94.setContinent(Continent.NORTH_AMERICA);
        t14.setName("Alaska");
        t24.setName("Northwest Territory");
        t34.setName("Greenland");
        t44.setName("Alberta");
        t54.setName("Ontario");
        t64.setName("Quebec");
        t74.setName("Western United States");
        t84.setName("Eastern United States");
        t94.setName("Central America");
        int actual_bonus4 = rs.calculateContinentBonus(player4, gameState);
        assertEquals(5, actual_bonus4);

        // Europe
        Territory t15 = new Territory();
        Territory t25 = new Territory();
        Territory t35 = new Territory();
        Territory t45 = new Territory();
        Territory t55 = new Territory();
        Territory t65 = new Territory();
        Territory t75 = new Territory();
        List<Territory> controlled_territories5 = List.of(t15, t25, t35, t45, t55, t65, t75);
        Player player5 = new Player(1, "A", "Red", 0, controlled_territories5);
        t15.setOwner(player5);
        t25.setOwner(player5);
        t35.setOwner(player5);
        t45.setOwner(player5);
        t55.setOwner(player5);
        t65.setOwner(player5);
        t75.setOwner(player5);
        t15.setArmyCount(3);
        t25.setArmyCount(3);
        t35.setArmyCount(3);
        t45.setArmyCount(3);
        t55.setArmyCount(3);
        t65.setArmyCount(3);
        t75.setArmyCount(3);
        t15.setContinent(Continent.EUROPE);
        t25.setContinent(Continent.EUROPE);
        t35.setContinent(Continent.EUROPE);
        t45.setContinent(Continent.EUROPE);
        t55.setContinent(Continent.EUROPE);
        t65.setContinent(Continent.EUROPE);
        t75.setContinent(Continent.EUROPE);
        t15.setName("Iceland");
        t25.setName("Scandinavia");
        t35.setName("Ukraine");
        t45.setName("Great Britain");
        t55.setName("Northern Europe");
        t65.setName("Western Europe");
        t75.setName("Southern Europe");
        int actual_bonus5 = rs.calculateContinentBonus(player5, gameState);
        assertEquals(5, actual_bonus5);

        // Asia
        Territory t16 = new Territory();
        Territory t26 = new Territory();
        Territory t36 = new Territory();
        Territory t46 = new Territory();
        Territory t56 = new Territory();
        Territory t66 = new Territory();
        Territory t76 = new Territory();
        Territory t86 = new Territory();
        Territory t96 = new Territory();
        Territory t106 = new Territory();
        Territory t116 = new Territory();
        Territory t126 = new Territory();
        List<Territory> controlled_territories6 = List.of(t16, t26, t36, t46, t56, t66, t76, t86, t96, t106, t116, t126);
        Player player6 = new Player(1, "A", "Red", 0, controlled_territories6);
        t16.setOwner(player6);
        t26.setOwner(player6);
        t36.setOwner(player6);
        t46.setOwner(player6);
        t56.setOwner(player6);
        t66.setOwner(player6);
        t76.setOwner(player6);
        t86.setOwner(player6);
        t96.setOwner(player6);
        t106.setOwner(player6);
        t116.setOwner(player6);
        t126.setOwner(player6);
        t16.setArmyCount(3);
        t26.setArmyCount(3);
        t36.setArmyCount(3);
        t46.setArmyCount(3);
        t56.setArmyCount(3);
        t66.setArmyCount(3);
        t76.setArmyCount(3);
        t86.setArmyCount(3);
        t96.setArmyCount(3);
        t106.setArmyCount(3);
        t116.setArmyCount(3);
        t126.setArmyCount(3);
        t16.setContinent(Continent.ASIA);
        t26.setContinent(Continent.ASIA);
        t36.setContinent(Continent.ASIA);
        t46.setContinent(Continent.ASIA);
        t56.setContinent(Continent.ASIA);
        t66.setContinent(Continent.ASIA);
        t76.setContinent(Continent.ASIA);
        t86.setContinent(Continent.ASIA);
        t96.setContinent(Continent.ASIA);
        t106.setContinent(Continent.ASIA);
        t116.setContinent(Continent.ASIA);
        t126.setContinent(Continent.ASIA);
        t16.setName("Ural");
        t26.setName("Siberia");
        t36.setName("Yakutsk");
        t46.setName("Kamchatka");
        t56.setName("Irkutsk");
        t66.setName("Mongolia");
        t76.setName("Japan");
        t86.setName("Afghanistan");
        t96.setName("China");
        t106.setName("Middle East");
        t116.setName("India");
        t126.setName("Siam");
        int actual_bonus6 = rs.calculateContinentBonus(player6, gameState);
        assertEquals(7, actual_bonus6);

    }

    @Test
    void shouldReturnCombinedBonusWhenPlayerControlsMultipleContinents() {
        // 1 player created, each controls 2 continents
        ReinforcementService rs = new ReinforcementService();
        Territory t1 = new Territory();
        Territory t2 = new Territory();
        Territory t3 = new Territory();
        Territory t4 = new Territory();
        Territory t5 = new Territory();
        Territory t6 = new Territory();
        Territory t7 = new Territory();
        Territory t8 = new Territory();
        Territory t9 = new Territory();
        Territory t10 = new Territory();
        GameState gameState = new GameState();
        List<Territory> controlled_territories = List.of(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
        Player player1 = new Player(1, "A", "Red", 0, controlled_territories);
        t1.setOwner(player1);
        t2.setOwner(player1);
        t3.setOwner(player1);
        t4.setOwner(player1);
        t5.setOwner(player1);
        t6.setOwner(player1);
        t7.setOwner(player1);
        t8.setOwner(player1);
        t9.setOwner(player1);
        t10.setOwner(player1);
        t1.setArmyCount(3);
        t2.setArmyCount(3);
        t3.setArmyCount(3);
        t4.setArmyCount(3);
        t5.setArmyCount(3);
        t6.setArmyCount(3);
        t7.setArmyCount(3);
        t8.setArmyCount(3);
        t9.setArmyCount(3);
        t10.setArmyCount(3);
        t1.setContinent(Continent.AFRICA);
        t2.setContinent(Continent.AFRICA);
        t3.setContinent(Continent.AFRICA);
        t4.setContinent(Continent.AFRICA);
        t5.setContinent(Continent.AFRICA);
        t6.setContinent(Continent.AFRICA);
        t7.setContinent(Continent.AUSTRALIA);
        t8.setContinent(Continent.AUSTRALIA);
        t9.setContinent(Continent.AUSTRALIA);
        t10.setContinent(Continent.AUSTRALIA);
        t1.setName("Egypt");
        t2.setName("Congo");
        t3.setName("Madagascar");
        t4.setName("East Africa");
        t5.setName("South Africa");
        t6.setName("Northern Africa");
        t7.setName("Indonesia");
        t8.setName("New Guinea");
        t9.setName("Western Australia");
        t10.setName("Eastern Australia");
        int actual_bonus = rs.calculateContinentBonus(player1, gameState);
        assertEquals(5, actual_bonus);

    }

    @Test
    void shouldNotGrantBonusWhenOneTerritoryInContinentIsOwnedByAnotherPlayer() {
        // one continent, 2 players, all but one go to one player
        ReinforcementService rs = new ReinforcementService();
        GameState gameState = new GameState();
        Territory t1 = new Territory();
        Territory t2 = new Territory();
        Territory t3 = new Territory();
        Territory t4 = new Territory();
        List<Territory> controlled_territories1 = List.of(t1, t2, t3);
        List<Territory> controlled_territories2 = List.of(t4);
        Player player1 = new Player(1, "A", "Red", 0, controlled_territories1);
        Player player2 = new Player(2, "B", "Yellow", 0, controlled_territories2);
        t1.setOwner(player1);
        t2.setOwner(player1);
        t3.setOwner(player1);
        t4.setOwner(player2);
        t1.setArmyCount(3);
        t2.setArmyCount(3);
        t3.setArmyCount(3);
        t4.setArmyCount(3);
        t1.setContinent(Continent.AUSTRALIA);
        t2.setContinent(Continent.AUSTRALIA);
        t3.setContinent(Continent.AUSTRALIA);
        t4.setContinent(Continent.AUSTRALIA);
        t1.setName("Indonesia");
        t2.setName("New Guinea");
        t3.setName("Western Australia");
        t4.setName("Eastern Australia");
        int actual_bonus1 = rs.calculateContinentBonus(player1, gameState);
        assertEquals(0, actual_bonus1);
        int actual_bonus2 = rs.calculateContinentBonus(player2, gameState);
        assertEquals(0, actual_bonus2);
    }

}
